### PR TITLE
refactor:  #302 feed and stories view consolidated into a single script for reducing code duplication

### LINKED ISSUE #302: refactor: change how feed is handled to match the logic for stories
Currently, `list-media-display.tsx` and `story-display.tsx` duplicate very similar functionality. Both implement a split-screen view for the list and the content, but they aren't reusing the same core logic.

To improve modularity and keep the codebase consistency, I think we should merge these into a single, reusable component. I propose naming this unified implementation `list-detail-display.tsx`. This name aligns with standard UI terminology and is broad enough to support feeds, stories, and any future media layouts that require this pattern.

`Story Display` currently includes some implementation details that are missing from `List Media Display` (such as receiving the client as a parameter). Because of this, the feed logic will need some refinement to align with the story logic so they can share the new unified component.

### PR DESCRIPTION
**Pull request by Quimisagi**
Closes https://github.com/supreme-gg-gg/instagram-cli/issues/302

## Summary

In this PR `story-display.tsx `and `list-media-display.tsx` were consolidated into a single file `list-detail-display.tsx ` , reducing code duplication and attempting to create a more generic split-list/detail UI component that can be reused. There is no any functional change  so its expected to behave totally the same as before.

Since both `stories` and `posts` had slightly different structures, it took me a while to think of a way to make them both fit a single generic data schema, but I managed to accomplish it by introducing new data types. I wonder if it was worth it, since nothing functional changes, but it was bugging me having different implementations for `feed` and `stories` despite them behaving pretty similarly  lol.

Also I firstly thought about doing this refactoring when I was about to start doing https://github.com/supreme-gg-gg/instagram-cli/issues/212, but I noticed that since `stories` and `feed` were handled by different scripts, it would require duplicating the same functionality for both.

#### New components:
- `source/ui/components/list-detail-display.tsx` — Unified component supporting both mode="story" and mode="post" with conditional features (search, mark-as-seen for stories; caption/likes/comments for posts)

#### Updated types (instagram.ts):
- Added `ListMediaItem<T, M>` generic type with pk, label, content fields
- `Story`, `Post`, `CarouselItem`, `PostMetadata` types aligned as `BaseMedia` + `MediaItemMetadata` extensions
#### Updated hooks:
- `use-stories.ts` — Returns ListMediaItem<Story>[] instead of StoryReel[]; uses pk for API calls, label for sidebar display
#### Removed files:
- `story-display.tsx`, l`ist-media-display.tsx` — Replaced by `list-detail-display.tsx`

## Testing

- [x] `npm run build`
- [x] `npm run lint-check` (0 errors, 6 warnings)
- [x] `npm test` (111 tests passed, 4 tests skipped)
- [x] Live run testing

## Future Work

- I noticed there may be not enough tests for `stories` and `feed` so its hard to know if any change had broken something.
-  Using feed in 'Timeline' mode is not working properly, but looks like it was not working before the refactor either. (Probably we should deprecate the 'Timeline' mode anyway)
-  `feed` still does not have some features that are in `stories`, such as user search (don't know if its even necessary)
- Some bugs and issues are still there (flickering, same stories displayed more than once in the list, etc)

### CODE REVIEW

**Review by supreme-gg-gg — COMMENTED** [review]
@Quimisagi thanks for the PR! I tried timeline mode and it should be working before the refactor, but I think we should deprecate and just remove it. The issue here seems to be that it's now rendered in an alternate buffer so it disappears after rendering.

Our current plan is to standardise the UI to using TUI for all user-facing pages, and switching to CLI mode for AI usage, so timeline mode does not really fit in that experience. It is also not the best UX to just dump the posts in a "timeline" instead of having an interactive window. cc @endernoke wdyt

**Review by endernoke — COMMENTED** [review]
@Quimisagi I got a bunch of typescript errors when building. Could you make sure the build is clean?

```
> @i7m/instagram-cli@1.5.0 build
> tsc --noEmit && node esbuild.config.mjs --production

source/client.ts(36,2): error TS2305: Module '"./types/instagram.js"' has no exported member 'StoryReel'.
source/commands/feed.tsx(5,14): error TS2305: Module '"../types/instagram.js"' has no exported member 'FeedInstance'.
source/mocks/mock-client.ts(15,2): error TS2305: Module '"../types/instagram.js"' has no exported member 'StoryReel'.
source/mocks/mock-data.ts(6,2): error TS2305: Module '"../types/instagram.js"' has no exported member 'FeedInstance'.
source/ui/components/list-detail-display.tsx(156,11): error TS2741: Property 'pk' is missing in type '{ label: string; content: Story[]; }' but required in type 'ListMediaItem<Story>'.
source/ui/hooks/use-stories.ts(5,7): error TS2305: Module '"../../types/instagram.js"' has no exported member 'StoryReel'.
source/ui/hooks/use-stories.ts(5,7): error TS6133: 'StoryReel' is declared but its value is never read.
source/ui/views/feed-view.tsx(31,8): error TS2322: Type '{ pk: number; label: string; content: { user: { pk: number; username: string; profilePicUrl?: string | undefined; }; taken_at: number; id: string; media_type: number; image_versions2?: { candidates: MediaCandidate[]; } | undefined; video_versions?: MediaCandidate[] | undefined; }[]; additional_metadata: { ...; }; }[]' is not assignable to type 'ListMediaItem<Post, PostMetadata>[]'.
  Type '{ pk: number; label: string; content: { user: { pk: number; username: string; profilePicUrl?: string; }; taken_at: number; id: string; media_type: number; image_versions2?: { candidates: MediaCandidate[]; }; video_versions?: MediaCandidate[]; }[]; additional_metadata: { ...; }; }' is not assignable to type 'ListMediaItem<Post, PostMetadata>'.
    Types of property 'content' are incompatible.
      Type '{ user: { pk: number; username: string; profilePicUrl?: string | undefined; }; taken_at: number; id: string; media_type: number; image_versions2?: { candidates: MediaCandidate[]; } | undefined; video_versions?: MediaCandidate[] | undefined; }[]' is not assignable to type 'Post[]'.
        Type '{ user: { pk: number; username: string; profilePicUrl?: string; }; taken_at: number; id: string; media_type: number; image_versions2?: { candidates: MediaCandidate[]; }; video_versions?: MediaCandidate[]; }' is not assignable to type 'Post'.
          Type '{ user: { pk: number; username: string; profilePicUrl?: string | undefined; }; taken_at: number; id: string; media_type: number; image_versions2?: { candidates: MediaCandidate[]; } | undefined; video_versions?: MediaCandidate[] | undefined; }' is missing the following properties from type 'PostMetadata': like_count, comment_count
source/ui/views/feed-view.tsx(64,5): error TS2322: Type 'ListMediaItem<Post, PostMetadata>[]' is not assignable to type 'ListMediaItem[]'.
  Type 'ListMediaItem<Post, PostMetadata>' is not assignable to type 'ListMediaItem'.
    Type 'PostMetadata' is not assignable to type 'undefined'.

```

> Our current plan is to standardise the UI to using TUI for all user-facing pages, and switching to CLI mode for AI usage, so timeline mode does not really fit in that experience. It is also not the best UX to just dump the posts in a "timeline" instead of having an interactive window. cc @endernoke wdyt

Agreed, let's deprecate the timeline view and standardize TUI usage.

**Comment by Quimisagi** [comment]
> @Quimisagi I got a bunch of typescript errors when building. Could you make sure the build is clean?
> 
> ```
> > @i7m/instagram-cli@1.5.0 build
> > tsc --noEmit && node esbuild.config.mjs --production
> 
> source/client.ts(36,2): error TS2305: Module '"./types/instagram.js"' has no exported member 'StoryReel'.
> source/commands/feed.tsx(5,14): error TS2305: Module '"../types/instagram.js"' has no exported member 'FeedInstance'.
> source/mocks/mock-client.ts(15,2): error TS2305: Module '"../types/instagram.js"' has no exported member 'StoryReel'.
> source/mocks/mock-data.ts(6,2): error TS2305: Module '"../types/instagram.js"' has no exported member 'FeedInstance'.
> source/ui/components/list-detail-display.tsx(156,11): error TS2741: Property 'pk' is missing in type '{ label: string; content: Story[]; }' but required in type 'ListMediaItem<Story>'.
> source/ui/hooks/use-stories.ts(5,7): error TS2305: Module '"../../types/instagram.js"' has no exported member 'StoryReel'.
> source/ui/hooks/use-stories.ts(5,7): error TS6133: 'StoryReel' is declared but its value is never read.
> source/ui/views/feed-view.tsx(31,8): error TS2322: Type '{ pk: number; label: string; content: { user: { pk: number; username: string; profilePicUrl?: string | undefined; }; taken_at: number; id: string; media_type: number; image_versions2?: { candidates: MediaCandidate[]; } | undefined; video_versions?: MediaCandidate[] | undefined; }[]; additional_metadata: { ...; }; }[]' is not assignable to type 'ListMediaItem<Post, PostMetadata>[]'.
>   Type '{ pk: number; label: string; content: { user: { pk: number; username: string; profilePicUrl?: string; }; taken_at: number; id: string; media_type: number; image_versions2?: { candidates: MediaCandidate[]; }; video_versions?: MediaCandidate[]; }[]; additional_metadata: { ...; }; }' is not assignable to type 'ListMediaItem<Post, PostMetadata>'.
>     Types of property 'content' are incompatible.
>       Type '{ user: { pk: number; username: string; profilePicUrl?: string | undefined; }; taken_at: number; id: string; media_type: number; image_versions2?: { candidates: MediaCandidate[]; } | undefined; video_versions?: MediaCandidate[] | undefined; }[]' is not assignable to type 'Post[]'.
>         Type '{ user: { pk: number; username: string; profilePicUrl?: string; }; taken_at: number; id: string; media_type: number; image_versions2?: { candidates: MediaCandidate[]; }; video_versions?: MediaCandidate[]; }' is not assignable to type 'Post'.
>           Type '{ user: { pk: number; username: string; profilePicUrl?: string | undefined; }; taken_at: number; id: string; media_type: number; image_versions2?: { candidates: MediaCandidate[]; } | undefined; video_versions?: MediaCandidate[] | undefined; }' is missing the following properties from type 'PostMetadata': like_count, comment_count
> source/ui/views/feed-view.tsx(64,5): error TS2322: Type 'ListMediaItem<Post, PostMetadata>[]' is not assignable to type 'ListMediaItem[]'.
>   Type 'ListMediaItem<Post, PostMetadata>' is not assignable to type 'ListMediaItem'.
>     Type 'PostMetadata' is not assignable to type 'undefined'.
> ```
> 

Sorry, I didn't noticed. Gonna fix it.

> > Our current plan is to standardise the UI to using TUI for all user-facing pages, and switching to CLI mode for AI usage, so timeline mode does not really fit in that experience. It is also not the best UX to just dump the posts in a "timeline" instead of having an interactive window. cc @endernoke wdyt
> 
> Agreed, let's deprecate the timeline view and standardize TUI usage.

Ok, so I will create an issue for that!

**Comment by supreme-gg-gg** [comment]
> Ok, so I will create an issue for that!

I think we can just do it in this PR to remove timeline mode since you mentioned it isn't working anyways

**Comment by Quimisagi** [comment]
@supreme-gg-gg  @endernoke  
Ok, so I fixed the errors on build and totally deleted the Timeline feed type
No other issue found so far so I think its ready for review.

**Comment by Quimisagi** [comment]
Ok, I did get some issues with the changes introduced in https://github.com/supreme-gg-gg/instagram-cli/pull/341 lol

I thought I fixed it with a rebase, but the building is failing for some reason.
Any idea what to do?

**Comment by supreme-gg-gg** [comment]
> Ok, I did get some issues with the changes introduced in #341 lol
> 
> I thought I fixed it with a rebase, but the building is failing for some reason. Any idea what to do?

@Quimisagi I removed the `ink-text-input` component and you might still be using it in one of the list views, that's why it's failing to build, can you replace that with our own `TextInput` (since it has cursor support and other features needed elsewhere)? Sorry about that, this is supposed to go into the next major version so there're several breaking changes

File: source/ui/components/list-detail-display.tsx [hunk 1]
```diff
@@ -1,27 +1,29 @@
 import React, {useState, useEffect, useMemo, useRef} from 'react';
 import {Box, Text, useInput, useApp, useStdout} from 'ink';
 import open from 'open';
+import TextInput from 'ink-text-input';
```
Comment (supreme-gg-gg) [inline source/ui/components/list-detail-display.tsx]: Here specifically

**Comment by Quimisagi** [comment]
I think I fixed it but something is failing in the actions
Thought there were no problems at local...

File: source/ui/components/list-detail-display.tsx (hunk 1 above)
Comment (Quimisagi) [reply source/ui/components/list-detail-display.tsx]: Solved!

**Comment by supreme-gg-gg** [comment]
no worries it seems intermittent, passes on rerun. I'll review this soon

File: source/ui/components/list-detail-display.tsx [hunk 2]
```diff
@@ -3,25 +3,27 @@ import {Box, Text, useInput, useApp, useStdout} from 'ink';
...
 import {createContextualLogger} from '../../utils/logger.js';
 import {type InstagramClient} from '../../client.js';
-import TextInput from './text-input.js';
 import SplitView from './split-view.js';
 import MediaPane from './media-pane.js';
+import TextInput from './text-input.js';
 
 type Properties = {
-	readonly reels: StoryReel[];
+	readonly listItems: Array<ListMediaItem<any, any>>;
```
Comment (supreme-gg-gg) [inline source/ui/components/list-detail-display.tsx]: I like the `ListMediaItem<T, M>` generic but `listItems: Array<ListMediaItem<any, any>>` at the component boundary throws all of it away and you're repeatedly using `as unknown as Story` casts throughout. 

Either thread the generic through the component props, or use a discriminated union so the type-narrowing is safe instead of cast-based.

File: source/commands/feed.tsx [hunk 3]
```diff
@@ -48,7 +47,7 @@ export default function Feed({args}: Properties) {
 					// If no items, set an error or handle appropriately
 					// setError('No feed items found.'); // This would require adding setError to the hook or handling it here
 				} else {
-					setFeed({posts: items});
+					setFeed({posts: items as any});
```
Comment (supreme-gg-gg) [inline source/commands/feed.tsx:50]: as `Post[]`? avoid `as any` if possible since you're already introducing unified types

File: source/ui/components/timeline-media-display.tsx
Comment (supreme-gg-gg) [inline source/ui/components/timeline-media-display.tsx:1]: This file is probably no longer used and can be removed since we're removing timeline mode

**Review by supreme-gg-gg — CHANGES_REQUESTED** [review]
lgtm overall, some comments about types

**Review by supreme-gg-gg — APPROVED** [review]
lgtm 😄

**Comment by Quimisagi** [comment]
Thank you!
And sorry! xd
I didn't noticed it was already merged and kept working on some additional changes. Im going to create a new MR.
